import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import NavBar from "../app/src/Components/NavBar";
import Home from "../app/src/Components/Home";

export default function index({ mainStrings, homeStrings }) {
  return (
    <div>
      <Head>
        <title>{mainStrings.app_title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home strings={homeStrings} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // TODO: once deployed change the URL
  const strings = await fetch("http://localhost:3000/api/strings/strings").then(
    (res) => res.json()
  );
  const homeStrings = await fetch(
    "http://localhost:3000/api/strings/homeStrings"
  ).then((res) => res.json());

  const commonStrings = await fetch(
    "http://localhost:3000/api/strings/commonStrings"
  ).then((res) => res.json());

  return {
    props: {
      mainStrings: strings,
      homeStrings,
      commonStrings,
    },
  };
}
