import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import NavBar from "../app/src/Components/NavBar";
import Home from "../app/src/Components/Home";
import TimeLine from "../app/src/Components/TimeLine";

export default function index({
  mainStrings,
  homeStrings,
  commonStrings,
  timelineData,
}) {
  return (
    <div>
      <Head>
        <title>{mainStrings.app_title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home strings={homeStrings} />
        <TimeLine strings={commonStrings} timelineEvents={timelineData} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // TODO: once deployed change the URL

  const [
    { value: strings = {} },
    { value: homeStrings = {} },
    { value: commonStrings = {} },
    { value: timelineData = {} },
  ] = await Promise.allSettled([
    fetch("http://localhost:3000/api/strings/strings").then((res) =>
      res.json()
    ),
    fetch("http://localhost:3000/api/strings/homeStrings").then((res) =>
      res.json()
    ),
    fetch("http://localhost:3000/api/strings/commonStrings").then((res) =>
      res.json()
    ),
    fetch("http://localhost:3000/api/data/timelineData").then((res) =>
      res.json()
    ),
  ]);

  return {
    props: {
      mainStrings: strings,
      homeStrings,
      commonStrings,
      timelineData,
    },
  };
}
